from store_api.supplier_payment_register import build_supplier_payment_register


def test_build_supplier_payment_register_summarizes_method_mix_and_remaining_outstanding():
    report = build_supplier_payment_register(
        branch_id="branch-1",
        supplier_payments=[
            {
                "id": "spay-1",
                "branch_id": "branch-1",
                "purchase_invoice_id": "pinv-1",
                "supplier_id": "supplier-1",
                "payment_number": "SPAY-2526-000001",
                "payment_date": "2026-04-12",
                "amount": 100.0,
                "payment_method": "bank_transfer",
                "reference": "UTR-001",
            },
            {
                "id": "spay-2",
                "branch_id": "branch-1",
                "purchase_invoice_id": "pinv-2",
                "supplier_id": "supplier-2",
                "payment_number": "SPAY-2526-000002",
                "payment_date": "2026-04-11",
                "amount": 50.0,
                "payment_method": "cash",
                "reference": "CASH-001",
            },
            {
                "id": "spay-3",
                "branch_id": "branch-1",
                "purchase_invoice_id": "pinv-1",
                "supplier_id": "supplier-1",
                "payment_number": "SPAY-2526-000003",
                "payment_date": "2026-04-13",
                "amount": 195.0,
                "payment_method": "upi",
                "reference": "UPI-001",
            },
        ],
        purchase_invoices=[
            {
                "id": "pinv-1",
                "branch_id": "branch-1",
                "supplier_id": "supplier-1",
                "invoice_number": "SPINV-2526-000011",
                "grand_total": 354.0,
            },
            {
                "id": "pinv-2",
                "branch_id": "branch-1",
                "supplier_id": "supplier-2",
                "invoice_number": "SPINV-2526-000012",
                "grand_total": 118.0,
            },
        ],
        supplier_returns=[
            {"id": "sret-1", "purchase_invoice_id": "pinv-1", "grand_total": 59.0},
        ],
        suppliers_by_id={
            "supplier-1": {"id": "supplier-1", "name": "Paper Supply Co"},
            "supplier-2": {"id": "supplier-2", "name": "Ink Wholesale"},
        },
    )

    assert report == {
        "branch_id": "branch-1",
        "payment_count": 3,
        "supplier_count": 2,
        "paid_total": 345.0,
        "bank_transfer_total": 100.0,
        "cash_total": 50.0,
        "upi_total": 195.0,
        "other_total": 0.0,
        "latest_payment_date": "2026-04-13",
        "records": [
            {
                "payment_id": "spay-3",
                "payment_number": "SPAY-2526-000003",
                "payment_date": "2026-04-13",
                "supplier_id": "supplier-1",
                "supplier_name": "Paper Supply Co",
                "purchase_invoice_id": "pinv-1",
                "purchase_invoice_number": "SPINV-2526-000011",
                "payment_method": "upi",
                "reference": "UPI-001",
                "amount": 195.0,
                "invoice_grand_total": 354.0,
                "invoice_credit_note_total": 59.0,
                "invoice_paid_total_after_payment": 295.0,
                "remaining_outstanding_total": 0.0,
                "settlement_status_after_payment": "SETTLED",
            },
            {
                "payment_id": "spay-1",
                "payment_number": "SPAY-2526-000001",
                "payment_date": "2026-04-12",
                "supplier_id": "supplier-1",
                "supplier_name": "Paper Supply Co",
                "purchase_invoice_id": "pinv-1",
                "purchase_invoice_number": "SPINV-2526-000011",
                "payment_method": "bank_transfer",
                "reference": "UTR-001",
                "amount": 100.0,
                "invoice_grand_total": 354.0,
                "invoice_credit_note_total": 59.0,
                "invoice_paid_total_after_payment": 100.0,
                "remaining_outstanding_total": 195.0,
                "settlement_status_after_payment": "PARTIALLY_SETTLED",
            },
            {
                "payment_id": "spay-2",
                "payment_number": "SPAY-2526-000002",
                "payment_date": "2026-04-11",
                "supplier_id": "supplier-2",
                "supplier_name": "Ink Wholesale",
                "purchase_invoice_id": "pinv-2",
                "purchase_invoice_number": "SPINV-2526-000012",
                "payment_method": "cash",
                "reference": "CASH-001",
                "amount": 50.0,
                "invoice_grand_total": 118.0,
                "invoice_credit_note_total": 0.0,
                "invoice_paid_total_after_payment": 50.0,
                "remaining_outstanding_total": 68.0,
                "settlement_status_after_payment": "PARTIALLY_SETTLED",
            },
        ],
    }
