from datetime import date

from store_api.supplier_payment_run import build_supplier_payment_run


def test_build_supplier_payment_run_groups_due_exposure_by_supplier():
    report = build_supplier_payment_run(
        branch_id="branch-1",
        as_of_date=date(2026, 4, 13),
        purchase_invoices=[
            {
                "id": "pinv-1",
                "branch_id": "branch-1",
                "supplier_id": "supplier-1",
                "invoice_number": "SPINV-2526-000001",
                "invoice_date": "2026-04-01",
                "payment_terms_days": 7,
                "grand_total": 236.0,
            },
            {
                "id": "pinv-2",
                "branch_id": "branch-1",
                "supplier_id": "supplier-1",
                "invoice_number": "SPINV-2526-000002",
                "invoice_date": "2026-04-13",
                "payment_terms_days": 0,
                "grand_total": 354.0,
            },
            {
                "id": "pinv-3",
                "branch_id": "branch-1",
                "supplier_id": "supplier-2",
                "invoice_number": "SPINV-2526-000003",
                "invoice_date": "2026-04-13",
                "payment_terms_days": 7,
                "grand_total": 59.0,
            },
            {
                "id": "pinv-4",
                "branch_id": "branch-1",
                "supplier_id": "supplier-2",
                "invoice_number": "SPINV-2526-000004",
                "invoice_date": "2026-04-10",
                "due_date": "2026-05-05",
                "payment_terms_days": 14,
                "grand_total": 118.0,
            },
            {
                "id": "pinv-5",
                "branch_id": "branch-1",
                "supplier_id": "supplier-3",
                "invoice_number": "SPINV-2526-000005",
                "invoice_date": "2026-04-10",
                "due_date": "2026-06-30",
                "payment_terms_days": 14,
                "grand_total": 236.0,
            },
            {
                "id": "pinv-6",
                "branch_id": "branch-1",
                "supplier_id": "supplier-3",
                "invoice_number": "SPINV-2526-000006",
                "invoice_date": "2026-03-01",
                "payment_terms_days": 30,
                "grand_total": 118.0,
            },
        ],
        supplier_returns=[
            {"id": "sret-1", "purchase_invoice_id": "pinv-2", "grand_total": 59.0},
        ],
        supplier_payments=[
            {"id": "spay-1", "purchase_invoice_id": "pinv-1", "amount": 100.0},
            {"id": "spay-2", "purchase_invoice_id": "pinv-6", "amount": 118.0},
        ],
        suppliers_by_id={
            "supplier-1": {"id": "supplier-1", "name": "Paper Supply Co", "payment_terms_days": 7},
            "supplier-2": {"id": "supplier-2", "name": "Ink Wholesale", "payment_terms_days": 7},
            "supplier-3": {"id": "supplier-3", "name": "Tape Traders", "payment_terms_days": 14},
        },
    )

    assert report == {
        "branch_id": "branch-1",
        "as_of_date": "2026-04-13",
        "supplier_count": 3,
        "release_now_total": 431.0,
        "release_this_week_total": 490.0,
        "release_this_month_total": 608.0,
        "outstanding_total": 844.0,
        "records": [
            {
                "supplier_id": "supplier-1",
                "supplier_name": "Paper Supply Co",
                "open_invoice_count": 2,
                "overdue_total": 136.0,
                "due_today_total": 295.0,
                "due_in_7_days_total": 0.0,
                "due_in_8_30_days_total": 0.0,
                "due_later_total": 0.0,
                "release_now_total": 431.0,
                "release_this_week_total": 431.0,
                "release_this_month_total": 431.0,
                "outstanding_total": 431.0,
                "next_due_date": "2026-04-08",
                "next_due_invoice_number": "SPINV-2526-000001",
                "most_urgent_status": "OVERDUE",
            },
            {
                "supplier_id": "supplier-2",
                "supplier_name": "Ink Wholesale",
                "open_invoice_count": 2,
                "overdue_total": 0.0,
                "due_today_total": 0.0,
                "due_in_7_days_total": 59.0,
                "due_in_8_30_days_total": 118.0,
                "due_later_total": 0.0,
                "release_now_total": 0.0,
                "release_this_week_total": 59.0,
                "release_this_month_total": 177.0,
                "outstanding_total": 177.0,
                "next_due_date": "2026-04-20",
                "next_due_invoice_number": "SPINV-2526-000003",
                "most_urgent_status": "DUE_IN_7_DAYS",
            },
            {
                "supplier_id": "supplier-3",
                "supplier_name": "Tape Traders",
                "open_invoice_count": 1,
                "overdue_total": 0.0,
                "due_today_total": 0.0,
                "due_in_7_days_total": 0.0,
                "due_in_8_30_days_total": 0.0,
                "due_later_total": 236.0,
                "release_now_total": 0.0,
                "release_this_week_total": 0.0,
                "release_this_month_total": 0.0,
                "outstanding_total": 236.0,
                "next_due_date": "2026-06-30",
                "next_due_invoice_number": "SPINV-2526-000005",
                "most_urgent_status": "DUE_LATER",
            },
        ],
    }
