from datetime import date

from store_api.supplier_due_schedule import build_supplier_due_schedule


def test_build_supplier_due_schedule_buckets_open_invoices_by_due_date():
    report = build_supplier_due_schedule(
        branch_id="branch-1",
        as_of_date=date(2026, 4, 13),
        purchase_invoices=[
            {
                "id": "pinv-1",
                "branch_id": "branch-1",
                "supplier_id": "supplier-1",
                "invoice_number": "SPINV-2526-000001",
                "invoice_date": "2026-04-01",
                "payment_terms_days": 7,
                "grand_total": 236.0,
            },
            {
                "id": "pinv-2",
                "branch_id": "branch-1",
                "supplier_id": "supplier-1",
                "invoice_number": "SPINV-2526-000002",
                "invoice_date": "2026-04-13",
                "payment_terms_days": 0,
                "grand_total": 354.0,
            },
            {
                "id": "pinv-3",
                "branch_id": "branch-1",
                "supplier_id": "supplier-2",
                "invoice_number": "SPINV-2526-000003",
                "invoice_date": "2026-04-13",
                "payment_terms_days": 7,
                "grand_total": 59.0,
            },
            {
                "id": "pinv-4",
                "branch_id": "branch-1",
                "supplier_id": "supplier-2",
                "invoice_number": "SPINV-2526-000004",
                "invoice_date": "2026-04-10",
                "due_date": "2026-05-05",
                "payment_terms_days": 14,
                "grand_total": 118.0,
            },
            {
                "id": "pinv-5",
                "branch_id": "branch-1",
                "supplier_id": "supplier-3",
                "invoice_number": "SPINV-2526-000005",
                "invoice_date": "2026-04-10",
                "due_date": "2026-06-30",
                "payment_terms_days": 14,
                "grand_total": 236.0,
            },
            {
                "id": "pinv-6",
                "branch_id": "branch-1",
                "supplier_id": "supplier-3",
                "invoice_number": "SPINV-2526-000006",
                "invoice_date": "2026-03-01",
                "payment_terms_days": 30,
                "grand_total": 118.0,
            },
        ],
        supplier_returns=[
            {"id": "sret-1", "purchase_invoice_id": "pinv-2", "grand_total": 59.0},
        ],
        supplier_payments=[
            {"id": "spay-1", "purchase_invoice_id": "pinv-1", "amount": 100.0},
            {"id": "spay-2", "purchase_invoice_id": "pinv-6", "amount": 118.0},
        ],
        suppliers_by_id={
            "supplier-1": {"id": "supplier-1", "name": "Paper Supply Co", "payment_terms_days": 7},
            "supplier-2": {"id": "supplier-2", "name": "Ink Wholesale", "payment_terms_days": 7},
            "supplier-3": {"id": "supplier-3", "name": "Tape Traders", "payment_terms_days": 14},
        },
    )

    assert report == {
        "branch_id": "branch-1",
        "as_of_date": "2026-04-13",
        "open_invoice_count": 5,
        "overdue_invoice_count": 1,
        "overdue_total": 136.0,
        "due_today_total": 295.0,
        "due_in_7_days_total": 59.0,
        "due_in_8_30_days_total": 118.0,
        "due_later_total": 236.0,
        "outstanding_total": 844.0,
        "records": [
            {
                "purchase_invoice_id": "pinv-1",
                "purchase_invoice_number": "SPINV-2526-000001",
                "supplier_id": "supplier-1",
                "supplier_name": "Paper Supply Co",
                "invoice_date": "2026-04-01",
                "due_date": "2026-04-08",
                "payment_terms_days": 7,
                "grand_total": 236.0,
                "credit_note_total": 0.0,
                "paid_total": 100.0,
                "outstanding_total": 136.0,
                "days_until_due": -5,
                "due_status": "OVERDUE",
            },
            {
                "purchase_invoice_id": "pinv-2",
                "purchase_invoice_number": "SPINV-2526-000002",
                "supplier_id": "supplier-1",
                "supplier_name": "Paper Supply Co",
                "invoice_date": "2026-04-13",
                "due_date": "2026-04-13",
                "payment_terms_days": 0,
                "grand_total": 354.0,
                "credit_note_total": 59.0,
                "paid_total": 0.0,
                "outstanding_total": 295.0,
                "days_until_due": 0,
                "due_status": "DUE_TODAY",
            },
            {
                "purchase_invoice_id": "pinv-3",
                "purchase_invoice_number": "SPINV-2526-000003",
                "supplier_id": "supplier-2",
                "supplier_name": "Ink Wholesale",
                "invoice_date": "2026-04-13",
                "due_date": "2026-04-20",
                "payment_terms_days": 7,
                "grand_total": 59.0,
                "credit_note_total": 0.0,
                "paid_total": 0.0,
                "outstanding_total": 59.0,
                "days_until_due": 7,
                "due_status": "DUE_IN_7_DAYS",
            },
            {
                "purchase_invoice_id": "pinv-4",
                "purchase_invoice_number": "SPINV-2526-000004",
                "supplier_id": "supplier-2",
                "supplier_name": "Ink Wholesale",
                "invoice_date": "2026-04-10",
                "due_date": "2026-05-05",
                "payment_terms_days": 14,
                "grand_total": 118.0,
                "credit_note_total": 0.0,
                "paid_total": 0.0,
                "outstanding_total": 118.0,
                "days_until_due": 22,
                "due_status": "DUE_IN_8_30_DAYS",
            },
            {
                "purchase_invoice_id": "pinv-5",
                "purchase_invoice_number": "SPINV-2526-000005",
                "supplier_id": "supplier-3",
                "supplier_name": "Tape Traders",
                "invoice_date": "2026-04-10",
                "due_date": "2026-06-30",
                "payment_terms_days": 14,
                "grand_total": 236.0,
                "credit_note_total": 0.0,
                "paid_total": 0.0,
                "outstanding_total": 236.0,
                "days_until_due": 78,
                "due_status": "DUE_LATER",
            },
        ],
    }
