from datetime import date

from store_api.supplier_escalations import build_supplier_escalation_report


def test_build_supplier_escalation_report_prioritizes_blocked_and_stale_cases():
    report = build_supplier_escalation_report(
        branch_id="branch-1",
        as_of_date=date(2026, 4, 13),
        purchase_invoices=[
            {
                "id": "pinv-1",
                "branch_id": "branch-1",
                "supplier_id": "supplier-1",
                "invoice_number": "SPINV-2526-000001",
                "invoice_date": "2026-03-11",
                "due_date": "2026-04-10",
                "payment_terms_days": 30,
                "grand_total": 354.0,
            },
            {
                "id": "pinv-2",
                "branch_id": "branch-1",
                "supplier_id": "supplier-2",
                "invoice_number": "SPINV-2526-000002",
                "invoice_date": "2026-04-13",
                "payment_terms_days": 7,
                "grand_total": 118.0,
            },
        ],
        supplier_returns=[
            {
                "id": "sret-1",
                "branch_id": "branch-1",
                "purchase_invoice_id": "pinv-1",
                "supplier_id": "supplier-1",
                "grand_total": 59.0,
            }
        ],
        supplier_payments=[
            {
                "id": "spay-1",
                "branch_id": "branch-1",
                "purchase_invoice_id": "pinv-1",
                "supplier_id": "supplier-1",
                "amount": 100.0,
            }
        ],
        vendor_disputes=[
            {
                "id": "vdis-1",
                "branch_id": "branch-1",
                "supplier_id": "supplier-1",
                "purchase_invoice_id": "pinv-1",
                "goods_receipt_id": None,
                "dispute_type": "RATE_MISMATCH",
                "status": "OPEN",
                "opened_on": "2026-04-01",
            },
            {
                "id": "vdis-2",
                "branch_id": "branch-1",
                "supplier_id": "supplier-2",
                "purchase_invoice_id": "pinv-2",
                "goods_receipt_id": None,
                "dispute_type": "SHORT_SUPPLY",
                "status": "OPEN",
                "opened_on": "2026-04-11",
            },
            {
                "id": "vdis-3",
                "branch_id": "branch-1",
                "supplier_id": "supplier-3",
                "purchase_invoice_id": None,
                "goods_receipt_id": "grn-3",
                "dispute_type": "DAMAGED_STOCK",
                "status": "OPEN",
                "opened_on": "2026-04-12",
            },
            {
                "id": "vdis-4",
                "branch_id": "branch-1",
                "supplier_id": "supplier-4",
                "purchase_invoice_id": None,
                "goods_receipt_id": "grn-4",
                "dispute_type": "MISSING_DOCS",
                "status": "OPEN",
                "opened_on": "2026-03-20",
            },
        ],
        goods_receipts=[
            {"id": "grn-3", "branch_id": "branch-1"},
            {"id": "grn-4", "branch_id": "branch-1"},
        ],
        suppliers_by_id={
            "supplier-1": {"id": "supplier-1", "name": "Paper Supply Co"},
            "supplier-2": {"id": "supplier-2", "name": "Ink Wholesale"},
            "supplier-3": {"id": "supplier-3", "name": "Box Makers"},
            "supplier-4": {"id": "supplier-4", "name": "Archive Traders"},
        },
    )

    assert report == {
        "branch_id": "branch-1",
        "as_of_date": "2026-04-13",
        "open_case_count": 4,
        "finance_escalation_count": 1,
        "owner_escalation_count": 1,
        "stale_case_count": 1,
        "branch_follow_up_count": 1,
        "blocked_release_now_total": 195.0,
        "blocked_release_this_week_total": 313.0,
        "blocked_outstanding_total": 313.0,
        "records": [
            {
                "dispute_id": "vdis-1",
                "supplier_id": "supplier-1",
                "supplier_name": "Paper Supply Co",
                "reference_type": "purchase_invoice",
                "reference_number": "SPINV-2526-000001",
                "dispute_type": "RATE_MISMATCH",
                "opened_on": "2026-04-01",
                "age_days": 12,
                "overdue": True,
                "hold_status": "HARD_HOLD",
                "blocked_release_now_total": 195.0,
                "blocked_release_this_week_total": 195.0,
                "blocked_outstanding_total": 195.0,
                "next_due_invoice_number": "SPINV-2526-000001",
                "most_urgent_status": "OVERDUE",
                "escalation_status": "FINANCE_ESCALATION",
                "escalation_target": "finance_admin",
                "next_action": "Freeze release and resolve invoice dispute before payment",
            },
            {
                "dispute_id": "vdis-2",
                "supplier_id": "supplier-2",
                "supplier_name": "Ink Wholesale",
                "reference_type": "purchase_invoice",
                "reference_number": "SPINV-2526-000002",
                "dispute_type": "SHORT_SUPPLY",
                "opened_on": "2026-04-11",
                "age_days": 2,
                "overdue": False,
                "hold_status": "SOFT_HOLD",
                "blocked_release_now_total": 0.0,
                "blocked_release_this_week_total": 118.0,
                "blocked_outstanding_total": 118.0,
                "next_due_invoice_number": "SPINV-2526-000002",
                "most_urgent_status": "DUE_IN_7_DAYS",
                "escalation_status": "OWNER_ESCALATION",
                "escalation_target": "tenant_owner",
                "next_action": "Owner follow-up before the next payment window",
            },
            {
                "dispute_id": "vdis-4",
                "supplier_id": "supplier-4",
                "supplier_name": "Archive Traders",
                "reference_type": "goods_receipt",
                "reference_number": "grn-4",
                "dispute_type": "MISSING_DOCS",
                "opened_on": "2026-03-20",
                "age_days": 24,
                "overdue": True,
                "hold_status": None,
                "blocked_release_now_total": 0.0,
                "blocked_release_this_week_total": 0.0,
                "blocked_outstanding_total": 0.0,
                "next_due_invoice_number": None,
                "most_urgent_status": None,
                "escalation_status": "STALE_CASE",
                "escalation_target": "tenant_owner",
                "next_action": "Escalate stale dispute and request supplier resolution date",
            },
            {
                "dispute_id": "vdis-3",
                "supplier_id": "supplier-3",
                "supplier_name": "Box Makers",
                "reference_type": "goods_receipt",
                "reference_number": "grn-3",
                "dispute_type": "DAMAGED_STOCK",
                "opened_on": "2026-04-12",
                "age_days": 1,
                "overdue": False,
                "hold_status": None,
                "blocked_release_now_total": 0.0,
                "blocked_release_this_week_total": 0.0,
                "blocked_outstanding_total": 0.0,
                "next_due_invoice_number": None,
                "most_urgent_status": None,
                "escalation_status": "BRANCH_FOLLOW_UP",
                "escalation_target": "store_manager",
                "next_action": "Branch follow-up and update dispute status",
            },
        ],
    }
